2018-07-29 12:54:28,470 - pipeline - ERROR - : Acquisition::GetAnalog(string) 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet3/Session1/Vicon/10.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 69, in save_features
    raw_data = self.get_raw_data(filepath, balance_board)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/sensor.py", line 52, in get_raw_data
    for label in labels]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/sensor.py", line 52, in <listcomp>
    for label in labels]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/btk.py", line 5028, in GetAnalog
    return _btk.btkAcquisition_GetAnalog(self, *args)
RuntimeError: Acquisition::GetAnalog(string)
Stack (most recent call last):
  File "feature_extraction.py", line 69, in <module>
    process_all_fp_files(cop_data_pipeline, fp_files)
  File "feature_extraction.py", line 29, in process_all_fp_files
    cop_data_pipeline.save_features(file)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 12:58:45,152 - pipeline - ERROR - : invalid value encountered in double_scalars 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet3/Session2/BalanceBoard/5.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 84, in save_features
    time_features = self.compute_time_features(preprocessed_cop_positions["COP_x"], preprocessed_cop_positions["COP_y"])
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 52, in compute_time_features
    time_domain_features = TimeFeatures(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 394, in __init__
    super(TimeFeatures, self).__init__(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 268, in __init__
    self.hybrid_features = self.compute_hybrid_features()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 373, in compute_hybrid_features
    features["Mean frequency"] = self.compute_mean_frequency()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 295, in compute_mean_frequency
    2 * np.pi * self.distance_features["Mean distance"])
RuntimeWarning: invalid value encountered in double_scalars
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 12:59:19,405 - pipeline - ERROR - : underflow encountered in multiply 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet2/Session1/BalanceBoard/12.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 76, in save_features
    preprocessed_cop_positions = self.preprocess_cop_positions(cop_positions, frequency, balance_board)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in preprocess_cop_positions
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in <listcomp>
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 82, in preprocess
    resampled_signal, analog_frequency)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 50, in apply_filtering
    filtered_signal = scipy.signal.filtfilt(b, a, input_signal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 3118, in filtfilt
    (y, zf) = lfilter(b, a, axis_reverse(y, axis=axis), axis=axis, zi=zi * y0)
RuntimeWarning: underflow encountered in multiply
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 13:00:16,701 - pipeline - ERROR - : underflow encountered in multiply 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet15/Session1/BalanceBoard/7.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 76, in save_features
    preprocessed_cop_positions = self.preprocess_cop_positions(cop_positions, frequency, balance_board)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in preprocess_cop_positions
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in <listcomp>
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 82, in preprocess
    resampled_signal, analog_frequency)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 50, in apply_filtering
    filtered_signal = scipy.signal.filtfilt(b, a, input_signal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 3118, in filtfilt
    (y, zf) = lfilter(b, a, axis_reverse(y, axis=axis), axis=axis, zi=zi * y0)
RuntimeWarning: underflow encountered in multiply
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 13:01:01,892 - pipeline - ERROR - : underflow encountered in multiply 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet13/Session1/BalanceBoard/3.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 76, in save_features
    preprocessed_cop_positions = self.preprocess_cop_positions(cop_positions, frequency, balance_board)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in preprocess_cop_positions
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in <listcomp>
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 82, in preprocess
    resampled_signal, analog_frequency)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 50, in apply_filtering
    filtered_signal = scipy.signal.filtfilt(b, a, input_signal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 3118, in filtfilt
    (y, zf) = lfilter(b, a, axis_reverse(y, axis=axis), axis=axis, zi=zi * y0)
RuntimeWarning: underflow encountered in multiply
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 13:02:54,253 - pipeline - ERROR - : invalid value encountered in double_scalars 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet16/Session1/BalanceBoard/5.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 84, in save_features
    time_features = self.compute_time_features(preprocessed_cop_positions["COP_x"], preprocessed_cop_positions["COP_y"])
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 52, in compute_time_features
    time_domain_features = TimeFeatures(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 394, in __init__
    super(TimeFeatures, self).__init__(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 268, in __init__
    self.hybrid_features = self.compute_hybrid_features()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 373, in compute_hybrid_features
    features["Mean frequency"] = self.compute_mean_frequency()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 295, in compute_mean_frequency
    2 * np.pi * self.distance_features["Mean distance"])
RuntimeWarning: invalid value encountered in double_scalars
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 13:03:31,996 - pipeline - ERROR - : invalid value encountered in double_scalars 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet18/Session2/BalanceBoard/9.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 84, in save_features
    time_features = self.compute_time_features(preprocessed_cop_positions["COP_x"], preprocessed_cop_positions["COP_y"])
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 52, in compute_time_features
    time_domain_features = TimeFeatures(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 394, in __init__
    super(TimeFeatures, self).__init__(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 268, in __init__
    self.hybrid_features = self.compute_hybrid_features()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 373, in compute_hybrid_features
    features["Mean frequency"] = self.compute_mean_frequency()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 295, in compute_mean_frequency
    2 * np.pi * self.distance_features["Mean distance"])
RuntimeWarning: invalid value encountered in double_scalars
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 13:04:12,513 - pipeline - ERROR - : underflow encountered in multiply 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet19/Session1/BalanceBoard/6.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 76, in save_features
    preprocessed_cop_positions = self.preprocess_cop_positions(cop_positions, frequency, balance_board)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in preprocess_cop_positions
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in <listcomp>
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 82, in preprocess
    resampled_signal, analog_frequency)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 50, in apply_filtering
    filtered_signal = scipy.signal.filtfilt(b, a, input_signal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 3118, in filtfilt
    (y, zf) = lfilter(b, a, axis_reverse(y, axis=axis), axis=axis, zi=zi * y0)
RuntimeWarning: underflow encountered in multiply
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 13:04:27,585 - pipeline - ERROR - : invalid value encountered in double_scalars 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet10/Session2/BalanceBoard/10.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 84, in save_features
    time_features = self.compute_time_features(preprocessed_cop_positions["COP_x"], preprocessed_cop_positions["COP_y"])
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 52, in compute_time_features
    time_domain_features = TimeFeatures(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 394, in __init__
    super(TimeFeatures, self).__init__(cop_x, cop_y)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 268, in __init__
    self.hybrid_features = self.compute_hybrid_features()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 373, in compute_hybrid_features
    features["Mean frequency"] = self.compute_mean_frequency()
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/time_features.py", line 295, in compute_mean_frequency
    2 * np.pi * self.distance_features["Mean distance"])
RuntimeWarning: invalid value encountered in double_scalars
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
2018-07-29 13:04:29,683 - pipeline - ERROR - : underflow encountered in multiply 
 Problem with file:/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/data/BalanceBoard_Static/Sujet10/Session2/BalanceBoard/9.c3d
Traceback (most recent call last):
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 76, in save_features
    preprocessed_cop_positions = self.preprocess_cop_positions(cop_positions, frequency, balance_board)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in preprocess_cop_positions
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 45, in <listcomp>
    preprocessed_data = [self.preprocess(data, frequency, balance_board) for data in cop_data]
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 82, in preprocess
    resampled_signal, analog_frequency)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/preprocess.py", line 50, in apply_filtering
    filtered_signal = scipy.signal.filtfilt(b, a, input_signal)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/signal/signaltools.py", line 3118, in filtfilt
    (y, zf) = lfilter(b, a, axis_reverse(y, axis=axis), axis=axis, zi=zi * y0)
RuntimeWarning: underflow encountered in multiply
Stack (most recent call last):
  File "feature_extraction.py", line 67, in <module>
    process_all_wbb_files(cop_data_pipeline, wbb_files)
  File "feature_extraction.py", line 19, in process_all_wbb_files
    cop_data_pipeline.save_features(file, balance_board=True)
  File "/Users/Antonin/Documents/VUB/semester 4/thesis/validation study/src/pipeline.py", line 93, in save_features
    logger.error(": {} \n Problem with file:{}".format(err, filepath), exc_info=True, stack_info=True)
